### ISSUE TITLE
Add support for M1

### ISSUE THREAD

**Issue by JohNan** [fluidsonic/fluid-time#1]
Kotlin 1.5.30 introduced support for more targets for Apple silicon. `macosArm64`, `iosSimulatorArm64`, `watchosSimulatorArm64`, and `tvosSimulatorArm64`

Would it be possible to update the kotlin version to be able to use this library on the new target?

To my understanding it would require you to update the kotlin version in the following gradle plugin: https://github.com/fluidsonic/fluid-gradle

**Comment by fluidsonic** [comment]
Thanks for bringing this up.
I've released version `0.15.0` :)
